### ISSUE TITLE
Still maintained or abandonded? Documentation outdated?

### ISSUE THREAD

**Issue by skjerns** [psychopy/psychopy-mri-emulator#1]
I'm struggeling to find good documentation on how to use this package with the current version of PsychoPy

- It seems like the documentation at https://psychopy.org/api/hardware/emulator.html is outdated (and also faulty)
- There is no mention of the plugin at https://plugins.psychopy.org/directory.html
- I cannot import the package using `import psychopy.hardware.emulator.SyncGenerator `
- Currently there is no documentation how to properly implement or use the package

Workaround:
- importing via `from psychopy_mri_emulator import launchScan` seems to work
- an error get's thrown: `AttributeError: 'str' object has no attribute 'reset'`
- However, I'm not sure if there are any side effects to that

Is the plugin abandoned? 

I would really like to have a simple way to register key presses coming from the scanner, however, I'm not sure that this package is still reliable enough to be used.

**Comment by TEParsons** [comment]
This one had fallen by the wayside, but isn't intentionally abandoned. I've made changes and done a new release, so if you reinstall the plugin & restart PsychoPy you should now be able to import SyncGenerator from `psychopy.hardware.emulator.SyncGenerator`.

**Comment by skjerns** [comment]
thanks! the plugin is still not compatible with 2024.2 due to some deprications and stubs.

I'll make a PR soon fixigin that :)
